### ISSUE TITLE
android.content.res.Resources$NotFoundException Resource ID #0x0

### ISSUE THREAD

**Issue by Joslyn-Chen** [XuDaojie/MultiStateView#3]
很多机型报这个错误
`
android.content.res.Resources.getValue(Resources.java:1289)
android.content.res.VivoResources.getValue(VivoResources.java:191)
android.content.res.Resources.loadXmlResourceParser(Resources.java:2725)
android.content.res.Resources.getLayout(Resources.java:1105)
android.view.LayoutInflater.inflate(LayoutInflater.java:418)
me.xdj.view.MultiStateView.setViewState(MultiStateView.java:87)
me.xdj.view.SimpleMultiStateView.setViewState(SimpleMultiStateView.java:85)
me.xdj.view.SimpleMultiStateView$1.run(SimpleMultiStateView.java:24)
`

**Comment by Joslyn-Chen** [comment]
copy 了原始项目，自行调整修改就好了。

**Comment by yeluodev** [comment]
@Joslyn-Chen 怎么改的兄弟
